### ISSUE TITLE
[Minor] Allows "next steps" date to be before "date applied" date

### ISSUE THREAD

**Issue by ashshah1** [info442-sp21/h-team#25] opened 2021-05-25 21:16 UTC
[Minor] On creating a new application, you can set the date for the next step to be before the date applied

**Comment by mariamatlick** [comment] 2021-05-27 21:21
Duplicate of #20: https://github.com/info442-sp21/h-team/issues/20

**Closed by mariamatlick** 2021-05-27 21:21 UTC
Labels: bug, duplicate

**Comment by cherimarie** [comment] 2021-06-01 22:21
For grading purposes, I won't consider this a duplicate, but it's fine to do so for issue organization.
