### ISSUE TITLE
Option to go to homepage from Sign-in page

### ISSUE THREAD

**Issue by yejukim** [info442-sp21/h-team#21] opened 2021-05-25 21:05 UTC
I think it would be a nice feature to click on the logo to refresh the home page or a way to get out of the sign-in page easily.

**Comment by mariamatlick** [comment] 2021-05-27 21:24
https://github.com/info442-sp21/h-team/issues/27 is a duplicate of this enhancement request

**Comment by mariamatlick** [comment] 2021-05-27 21:24
We could add a back button that navigates back to the landing page but since it is a web application, we thought it would be repetitive if we added a back button since users can simply just click on the back button on their browser.

**Comment by ifrahm** [comment] 2021-05-27 22:02
#41  is a duplicate of this enhancement request

**Comment by yiuchungcheung** [comment] 2021-06-03 21:56
Fixed this issue! Users can click on "Trackity" in the copyright footer to go back to the landing page

**Closed** 2021-06-03 21:56 UTC
Labels: enhancement, resolved
