### ISSUE TITLE
[minor] Sign in boxes disappear when clicked on

### ISSUE THREAD

**Issue by haileymeister** [info442-sp21/h-team#32] opened 2021-05-25 22:01 UTC
Minor: Sign in boxes disappear when you click on them which may cause the user to forget what they are supposed to type. Safari on macOS Big Sur. to reproduce this you click on the password box. 
<img width="598" alt="Screen Shot 2021-05-25 at 2 58 39 PM" src="https://user-images.githubusercontent.com/49212221/119574157-1ddae580-bd6a-11eb-9570-bf27cff52689.png">

**Comment by mariamatlick** [comment] 2021-05-27 21:03
This is the form format that we chose to use and it works as it is supposed to, but we understand how this could be confusing! We will look into another form format.

**Comment by mariamatlick** [comment] 2021-05-27 21:36
Duplicate of #16

**Closed by mariamatlick** 2021-05-27 21:36 UTC
Labels: bug
