### ISSUE TITLE
Feature request: add sign-up error messages/more instruction

### ISSUE THREAD

**Issue by abq14** [info442-sp21/h-team#39] opened 2021-05-26 02:02 UTC
The first time I tried to sign up I got an error message, but it didn't specify what was wrong. I realized that I forgot to fully type out my email address. 
![image](https://user-images.githubusercontent.com/30161847/119591380-55a65500-bd8b-11eb-8a0e-3a94877d6597.png)
The second time, I got an error message for what I assume was my password, but wasn't sure if that was the issue. That's why I suggest adding more specific error messages or being more clear about the sign-up requirements (e.g. adding a message that says "Your password must be x characters long and contain a number, etc."
![image](https://user-images.githubusercontent.com/30161847/119591468-825a6c80-bd8b-11eb-81cb-a816eb6a7f31.png)

I think this change would enhance the user experience when signing up. You might lose users who get frustrated with the sign up process.

**Comment by yiuchungcheung** [comment] 2021-05-27 21:57
This is a duplicate of #17

**Closed** 2021-05-27 21:59 UTC
Labels: enhancement
