### ISSUE TITLE
Stuck on sign-in or sign-up [minor]

### ISSUE THREAD

**Issue by diegot-stack** [info442-sp21/h-team#27] opened 2021-05-25 21:27 UTC
![Screen Shot 2021-05-25 at 2 23 05 PM](https://user-images.githubusercontent.com/56012534/119570370-def66100-bd64-11eb-88c8-e437d0bc8272.png)

![Screen Shot 2021-05-25 at 2 25 18 PM](https://user-images.githubusercontent.com/56012534/119570525-17963a80-bd65-11eb-9676-2677ab55dc60.png)

Once clicking on the sign in button, there is no way to navigate back to the "home page".

Steps to recreate:
1. Click on log or sign up

Environment: Desktop, Chrome (Version 90.0.4430.212) on macOS Mojave

**Comment by yiuchungcheung** [comment] 2021-05-27 21:18
We could add a back button that navigates back to the landing page but since it is a web application, we thought it would be repetitive if we added a back button since users can simply just click on the back button on their browser.

**Comment by mariamatlick** [comment] 2021-05-27 21:23
Duplicate of: https://github.com/info442-sp21/h-team/issues/21

**Closed by mariamatlick** 2021-05-27 21:23 UTC
Labels: invalid

**Comment by cherimarie** [comment] 2021-06-02 01:58
For grading purposes, I won't be counting this as a duplicate, but it's fine to do so for issue organization.
