### ISSUE TITLE
[Minor] Validation Error With New Job Post

### ISSUE THREAD

**Issue by kmarshall98** [info442-sp21/h-team#20] opened 2021-05-25 21:03 UTC
**Severity** Minor
**Description** Input box for when a user applied to the job does not have a validation date checker so the user is able to input that they applied to a job that is in the future when they should only be allowed to enter a date that already has passed. 
**Environment** Safari on macOS Big Sur 11.2.3
**Steps to Reproduce**
1) Navigate to websites home page.
2) Login or sign up for an account with Trackity.
3) Select the add a "New Application" button.
4) Select whether a job is active or not.
5) Enter the position and company.
6) Select the calendar button and for a date in the future.
Expected Outcome: User receives a message that they must enter a date that has already passed either there or before submitting the post.
Actual Outcome: User is able to enter a date in the future and save the post.
<img width="465" alt="Screen Shot 2021-05-25 at 2 11 57 PM" src="https://user-images.githubusercontent.com/46639384/119569133-2da2fb80-bd63-11eb-9061-f81086fb4a0d.png">

**Comment by kristina-te** [comment] 2021-05-25 21:11
Users should be required to select Active or Inactive because when left empty, it is automatically defaulted to Inactive without a selection. Either make it a requirement or perhaps set it default to Inactive so it makes logical sense.

**Comment by RaphaelKyle** [comment] 2021-05-25 21:26
Posting a new job post should also require a link to the application. I noticed that it only required a title and a description. It should probably require a bit more than that.

**Comment by mariamatlick** [comment] 2021-05-27 21:22
There is a duplicate of this post: https://github.com/info442-sp21/h-team/issues/25. We will fix this issue!

**Comment by mariamatlick** [comment] 2021-05-27 21:27
#25 is a duplicate of this

**Comment by yiuchungcheung** [comment] 2021-05-27 22:17
This is a valid issue, we will try to implement date validation in our next release, thank you so much for the feedback!

**Comment by yiuchungcheung** [comment] 2021-06-01 22:04
We have fixed this issue by restricting users' ability to choose dates past the current date for "date applied" and only allowing users to choose dates starting the current date for "next step date"!

**Comment by yiuchungcheung** [comment] 2021-06-01 22:04
https://github.com/info442-sp21/h-team/commit/2ac74bc1b6dc806d6132858eb76e50fe3e70d349

**Closed** 2021-06-03 21:32 UTC
Labels: bug, resolved
