### ISSUE TITLE
[minor] Sign up fails with valid email

### ISSUE THREAD

**Issue by ndemmel** [info442-sp21/h-team#17] opened 2021-05-25 21:00 UTC
Severity: Major
Description: Signing up for the site with a valid email and 4 character password results in an error and the account is not created.
Environment: Windows 10 Firefox 88.0.1
Steps to reproduce:
1. enter a valid email address in the email textbox
2. enter any 4 character password in the password textbox
3. retype the exact password in the last textbox

Actual result: red text shows up that says "Failed to create an account". No other changes occur on the page. There is no indication that the failure is due to user error.
Expected result: an account is created and I can then access the site. 

![signupfail](https://user-images.githubusercontent.com/37096923/119567719-840f3a80-bd61-11eb-913a-503b061ff816.PNG)

**Comment by yiuchungcheung** [comment] 2021-05-25 21:15
your password needs to be at least 8 characters! We will implement that error message

**Comment by mariamatlick** [comment] 2021-05-27 21:17
Invalid original bug (the email is valid, the password is the issue!), but we are considering it a minor usability bug to inform the users of password requirements

**Comment by yiuchungcheung** [comment] 2021-05-27 21:59
#39 is a duplicate of this issue

**Comment by ifrahm** [comment] 2021-05-27 22:14
We will implement this in our next release

**Comment by cherimarie** [comment] 2021-06-01 19:58
I would call this a major bug, as it prevents users from signing up to the service.

**Comment by yiuchungcheung** [comment] 2021-06-01 22:01
We have resolved this issue by adding some feedback with an error message, as well as adding a guideline indicating passwords needs to be at least 6 characters!

**Comment by yiuchungcheung** [comment] 2021-06-01 22:01
https://github.com/info442-sp21/h-team/commit/2ac74bc1b6dc806d6132858eb76e50fe3e70d349

**Closed** 2021-06-01 22:02 UTC
Labels: resolved
